### ISSUE TITLE
Advanced notifications

### ISSUE THREAD

**Issue by danimesq** [ZeroNetPlus/ZeroNetPlus#23]
- [ ] Images in notifications (#15)
- [ ] Mark notifications as readed (#18)
- [ ] "New notifications" and "Readed notifications" tab menu (#19)
- [ ] "Like", "Share" and other buttons a zite can use in notification (#20)
- [ ] Quick reply form in notification (#21)
- [ ] New design for notifications (#22)
